image: alpine/edge
packages:
  - go
  - nginx
tasks:
  - build: |
      cd go-pkg-proxy
      make build
  - check-example: |
      cd go-pkg-proxy
      make run \
        GO_PKG_PROXY_LOG_LEVEL=DEBUG \
        GO_PKG_PROXY_DRY_RUN=1 \
        GO_PKG_PROXY_MODULES=doc/example/go.json
  - test-nginx: |
      cd go-pkg-proxy
      ./test-nginx.py
  - check-doc: |
      cd go-pkg-proxy
      tools/is-clean --make --root=doc README.md
triggers:
  - action: email
    condition: always
    to: builds@rootmos.io
